/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation(project(":gameEngine"))
    implementation(project(":api"))

    // DDX framework
    implementation(libs.gdx.core)
    implementation(libs.gdx.backend)
    implementation(libs.gdx.natives) { artifact { classifier = "natives-desktop" } }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "it.unicam.cs.mpgc.rpg130398.GDX_DesktopLauncher"
}

// sets the working directory to the asset directory, so it is easy to access it
tasks.named<JavaExec>("run") {
    workingDir = file("assets")
}